### Database Properties
#spring.datasource.url = jdbc:mysql://localhost:33612/users_database?useSSL=false
#spring.datasource.username = root
#spring.datasource.password = root
#
#
### Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update

#H2 https://stackoverflow.com/questions/48409005/what-is-the-jdbc-connection-string-for-h2-database
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:33612/users_database?useSSL=false
        username: root 
    jpa:
        properties:
           hibernate: dialect:org.hibernate.dialect.MySQL8Dialect
        hibernate:
           ddl-auto: update        